title: Nuzlocke of the Weary King
description: 
theme: just-the-docs
color_scheme: dark

url: https://seraphshark.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-feed

authors:
  ralts-lover-69:
    icon: "defaulticon.png"
    name: "rhea🥺💕"
  jade-placeholder:
    icon: "defaulticon.png"
    name: "this is jades placeholder"
  biancasbestie:
    icon: "defaulticon.png"
    name: "touya"
  dragonitefucker:
    icon: "defaulticon.png"
    name: "Onion"
  louroxxx:
    icon: "defaulticon.png"
    name: "LOU!"
  sunflorafolk:
    icon: "defaulticon.png"
    name: "adrian"
  nounpleasantry:
    icon: "noah.png"
    name: "Noah"
  ghostposting:
    icon: "defaulticon.png"
    name: "Boo"
  assignedmetalhead:
    icon: "defaulticon.png"
    name: "Hikaru"
  mpreglover1999:
    icon: "defaulticon.png"
    name: "mpreg lover"
  ghetsisapologist:
    icon: "IMG_4710.jpg"
    name: "zander"
  strawberrywhippedcreamlemonzest:
    icon: "Tiffany_Profile_Photo.png"
    name: tiffany
  
