title: Nuzlocke of the Weary King
description: 
theme: just-the-docs
color_scheme: dark

url: https://seraphshark.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-feed

authors:
  ralts-lover-69:
    icon: {{ site.baseurl }}/assets/images/posts/defaulticon.png
    name: rhea
